config/routes.rb
Rails.application.routes.draw do
  get 'babies/index'
  resources :babies
  resources :breastfeedings
  root 'babies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
    has_many :breastfeedings, dependent: :destroy
    def feed_count
      breastfeedings.count
    end
    def feed_volume
      breastfeedings.sum(:volume)
    end
    def feed_time
      breastfeedings.sum(:feeding_time)
    end
    def feeding_times_today
      feed_today.count
    end
    def volume_today
      feed_today.sum(:volume)
    end
    def last_time
      breastfeedings.last.created_at
    end
    private
    def feed_today
      breastfeedings.where('created_at > ?', Date.today)
    end
  end

app/models/breastfeeding.rb
class Breastfeeding < ApplicationRecord
  belongs_to :baby
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all.includes(:breastfeedings) 
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
  end

  # GET /babies/new
  def new
    @baby = Baby.new
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Baby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baby_params
      params.require(:baby).permit(:name)
    end
end

app/controllers/breastfeedings_controller.rb
class BreastfeedingsController < ApplicationController
  before_action :set_breastfeeding, only: [:show, :edit, :update, :destroy]

  # GET /breastfeedings
  # GET /breastfeedings.json
  def index
    @breastfeedings = Breastfeeding.all
  end

  # GET /breastfeedings/1
  # GET /breastfeedings/1.json
  def show
  end

  # GET /breastfeedings/new
  def new
    @breastfeeding = Breastfeeding.new
  end

  # GET /breastfeedings/1/edit
  def edit
  end

  # POST /breastfeedings
  # POST /breastfeedings.json
  def create
    @breastfeeding = Breastfeeding.new(breastfeeding_params)

    respond_to do |format|
      if @breastfeeding.save
        format.html { redirect_to @breastfeeding, notice: 'Breastfeeding was successfully created.' }
        format.json { render :show, status: :created, location: @breastfeeding }
      else
        format.html { render :new }
        format.json { render json: @breastfeeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breastfeedings/1
  # PATCH/PUT /breastfeedings/1.json
  def update
    respond_to do |format|
      if @breastfeeding.update(breastfeeding_params)
        format.html { redirect_to @breastfeeding, notice: 'Breastfeeding was successfully updated.' }
        format.json { render :show, status: :ok, location: @breastfeeding }
      else
        format.html { render :edit }
        format.json { render json: @breastfeeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breastfeedings/1
  # DELETE /breastfeedings/1.json
  def destroy
    @breastfeeding.destroy
    respond_to do |format|
      format.html { redirect_to breastfeedings_url, notice: 'Breastfeeding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breastfeeding
      @breastfeeding = Breastfeeding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breastfeeding_params
      params.require(:breastfeeding).permit(:baby_id, :volume, :time_feeding)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/breastfeedings_helper.rb
module BreastfeedingsHelper
end

app/views/babies/_form.html.erb
<%= form_with(model: baby, local: true) do |form| %>
  <% if baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
      <% baby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/babies/edit.html.erb
<h1>Editing Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Show', @baby %> |
<%= link_to 'Back', babies_path %>

app/views/babies/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Babies</h1>
<table>


  <tbody>
    <% @babies.each do |baby| %>
    <%= baby.name %><br>
    <%= "El bebé ha tomado leche" %>
    <%= baby.control %>
        <%= "veces" %>
    <%= "con un total de" %>
    <%= baby.sum %>
    <%= "ml" %>
   <br>
<%= link_to 'Delete', baby, method: :delete, data: { conrfirm:" Seguro?" } %><br>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Baby', new_baby_path %>

app/views/babies/new.html.erb
<h1>New Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Back', babies_path %>

app/views/babies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @baby.name %>
  <strong>Veces hoy:</strong>
  <%= @baby.breastfeedings.where('created_at > ?', Date.today).count %>
  <strong>última vez:</strong>
  <strong>veces hoy</strong>
  <%= @baby.breastfeedings.where('created_at >?', Date.today).sum(:volume) %>
  <strong>Última vez</strong>
  <%= time_ago_in_words(@baby.breastfeedings.last.created_at) %>
</p>

<%= link_to 'Edit', edit_baby_path(@baby) %> |
<%= link_to 'Back', babies_path %>

app/views/breastfeedings/_form.html.erb
<%= form_with(model: breastfeeding, local: true) do |form| %>
  <% if breastfeeding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(breastfeeding.errors.count, "error") %> prohibited this breastfeeding from being saved:</h2>

      <ul>
      <% breastfeeding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :baby_id %>
    <%= form.text_field :baby_id %>
  </div>

  <div class="field">
    <%= form.label :volume %>
    <%= form.text_field :volume %>
  </div>

  <div class="field">
    <%= form.label :time_feeding %>
    <%= form.text_field :time_feeding %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/breastfeedings/edit.html.erb
<h1>Editing Breastfeeding</h1>

<%= render 'form', breastfeeding: @breastfeeding %>

<%= link_to 'Show', @breastfeeding %> |
<%= link_to 'Back', breastfeedings_path %>

app/views/breastfeedings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breastfeedings</h1>

<table>
  <thead>
    <tr>
      <th>Baby</th>
      <th>Volume</th>
      <th>Time feeding</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breastfeedings.each do |breastfeeding| %>
      <tr>
        <td><%= breastfeeding.baby %></td>
        <td><%= breastfeeding.volume %></td>
        <td><%= breastfeeding.time_feeding %></td>
        <td><%= link_to 'Show', breastfeeding %></td>
        <td><%= link_to 'Edit', edit_breastfeeding_path(breastfeeding) %></td>
        <td><%= link_to 'Destroy', breastfeeding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breastfeeding', new_breastfeeding_path %>

app/views/breastfeedings/new.html.erb
<h1>New Breastfeeding</h1>

<%= render 'form', breastfeeding: @breastfeeding %>

<%= link_to 'Back', breastfeedings_path %>

app/views/breastfeedings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Baby:</strong>
  <%= @breastfeeding.baby %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @breastfeeding.volume %>
</p>

<p>
  <strong>Time feeding:</strong>
  <%= @breastfeeding.time_feeding %>
</p>

<%= link_to 'Edit', edit_breastfeeding_path(@breastfeeding) %> |
<%= link_to 'Back', breastfeedings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>